const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      priceOld: 45,
      stars: 2,
      ownStars: 4,
      promo: 'sale',
      image: './images/fornitures-bed-1.jpg',
      newFurniture: true,
      isFavorite: true,
      compare: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-2.jpg',
      newFurniture: true,
      isFavorite: true,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-3.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-4.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-5.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-6.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-7.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-8.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-9.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-10.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-4.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-5.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-6.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-7.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-8.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-9.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      image: './images/fornitures-bed-10.jpg',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      compare: false,
    },
  ],
  cart: {
    products: [],
  },
  feedback: [
    {
      id: 1,
      author: 'Amanda Smith',
      authorTitle: 'Furniture Client',
      content:
        'Lorem ipsum dolor sit amet, etiam luptatum id vel, diam ornatus moderatius cu usu. Ad eos suas eripuit, vis ea.',
      photo: '/images/feedback/portrait1.png',
    },
    {
      id: 2,
      author: 'John Smith',
      authorTitle: 'Designer',
      content:
        'Lorem ipsum dolor sit amet, eam id aliquip eleifend. Nec no dico illud augue, ex nam fugit mandamus, no ullum laboramus vel? Et erroribus instructior.',
      photo: '/images/feedback/portrait2.png',
    },
    {
      id: 3,
      author: 'Tora Leaves',
      authorTitle: 'Immortal Actress',
      content:
        'Lorem ipsum dolor sit amet, pri ne prima theophrastus, iudico percipitur ne eam! Wisi putant in ius, etiam.',
      photo: '/images/feedback/portrait3.png',
    },
    {
      id: 4,
      author: 'Kari Karnes',
      authorTitle: 'Salesman',
      content:
        'Lorem ipsum dolor sit amet, eos tantas propriae at, erant delectus perpetua duo eu, enim idque voluptatum mea ea. Sit ei.',
      photo: '/images/feedback/portrait4.png',
    },
    {
      id: 5,
      author: 'Jean Claude',
      authorTitle: 'Partner',
      content:
        'Lorem ipsum dolor sit amet, habeo decore id vix. Te nam tollit nominati concludaturque. Usu principes reformidans eu. In pro inermis aliquando. Aperiri laoreet oporteat an mei, mel.',
      photo: '/images/feedback/portrait5.png',
    },
  ],
  settings: {
    mediaQuery: 'desktop',
  },
};

export default initialState;
